// 离线生成符号集并写入 src/shared/symbols.ts（确定性，可复现）。运行：npm run gen:symbols
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { generateSymbols } from "../core/symbolGen.ts";

const set = generateSymbols(8, 16, 0x5eed1234);
const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../shared/symbols.ts");

const lines: string[] = [];
lines.push("// AUTO-GENERATED by src/scripts/gen_symbols.ts — 禁止手改；重新生成请运行 npm run gen:symbols");
lines.push("// 符号集：8×8 二值点阵，16 个图案，最小汉明距离经离线寻优最大化（确定性种子 0x5eed1234）。");
lines.push(`export const SYMBOL_GRID = ${set.grid};`);
lines.push(`export const SYMBOL_COUNT = ${set.count};`);
lines.push(`export const SYMBOL_SET_MIN_DISTANCE = ${set.minDistance};`);
lines.push("export const SYMBOLS_8x8: number[][] = [");
for (const p of set.symbols) lines.push("  [" + p.join(",") + "],");
lines.push("];");
void writeFileSync(out, lines.join("\n") + "\n");
console.log(`symbols.ts 已写入 ${out}（最小汉明距离=${set.minDistance}）`);
